# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bonsai/proto/curve_generator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bonsai.proto import inkling_types_pb2 as bonsai_dot_proto_dot_inkling__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bonsai/proto/curve_generator.proto',
  package='bonsai.proto.curve_generator',
  syntax='proto3',
  serialized_pb=_b('\n\"bonsai/proto/curve_generator.proto\x12\x1c\x62onsai.proto.curve_generator\x1a bonsai/proto/inkling_types.proto\";\n&CurveGeneratorSetPropertiesRequestData\x12\x11\n\tcurviness\x18\x01 \x01(\x02\"J\n\x12Schema_MNIST_Input\x12\x34\n\x05image\x18\x01 \x01(\x0b\x32%.bonsai.inkling_types.proto.Luminance\"$\n\x13Schema_MNIST_Output\x12\r\n\x05label\x18\x01 \x01(\r\"a\n\x1aMNIST_training_data_schema\x12\r\n\x05label\x18\x01 \x01(\r\x12\x34\n\x05image\x18\x02 \x01(\x0b\x32%.bonsai.inkling_types.proto.Luminanceb\x06proto3')
  ,
  dependencies=[bonsai_dot_proto_dot_inkling__types__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CURVEGENERATORSETPROPERTIESREQUESTDATA = _descriptor.Descriptor(
  name='CurveGeneratorSetPropertiesRequestData',
  full_name='bonsai.proto.curve_generator.CurveGeneratorSetPropertiesRequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='curviness', full_name='bonsai.proto.curve_generator.CurveGeneratorSetPropertiesRequestData.curviness', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=161,
)


_SCHEMA_MNIST_INPUT = _descriptor.Descriptor(
  name='Schema_MNIST_Input',
  full_name='bonsai.proto.curve_generator.Schema_MNIST_Input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='bonsai.proto.curve_generator.Schema_MNIST_Input.image', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=237,
)


_SCHEMA_MNIST_OUTPUT = _descriptor.Descriptor(
  name='Schema_MNIST_Output',
  full_name='bonsai.proto.curve_generator.Schema_MNIST_Output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='bonsai.proto.curve_generator.Schema_MNIST_Output.label', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=275,
)


_MNIST_TRAINING_DATA_SCHEMA = _descriptor.Descriptor(
  name='MNIST_training_data_schema',
  full_name='bonsai.proto.curve_generator.MNIST_training_data_schema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='bonsai.proto.curve_generator.MNIST_training_data_schema.label', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='bonsai.proto.curve_generator.MNIST_training_data_schema.image', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=374,
)

_SCHEMA_MNIST_INPUT.fields_by_name['image'].message_type = bonsai_dot_proto_dot_inkling__types__pb2._LUMINANCE
_MNIST_TRAINING_DATA_SCHEMA.fields_by_name['image'].message_type = bonsai_dot_proto_dot_inkling__types__pb2._LUMINANCE
DESCRIPTOR.message_types_by_name['CurveGeneratorSetPropertiesRequestData'] = _CURVEGENERATORSETPROPERTIESREQUESTDATA
DESCRIPTOR.message_types_by_name['Schema_MNIST_Input'] = _SCHEMA_MNIST_INPUT
DESCRIPTOR.message_types_by_name['Schema_MNIST_Output'] = _SCHEMA_MNIST_OUTPUT
DESCRIPTOR.message_types_by_name['MNIST_training_data_schema'] = _MNIST_TRAINING_DATA_SCHEMA

CurveGeneratorSetPropertiesRequestData = _reflection.GeneratedProtocolMessageType('CurveGeneratorSetPropertiesRequestData', (_message.Message,), dict(
  DESCRIPTOR = _CURVEGENERATORSETPROPERTIESREQUESTDATA,
  __module__ = 'bonsai.proto.curve_generator_pb2'
  # @@protoc_insertion_point(class_scope:bonsai.proto.curve_generator.CurveGeneratorSetPropertiesRequestData)
  ))
_sym_db.RegisterMessage(CurveGeneratorSetPropertiesRequestData)

Schema_MNIST_Input = _reflection.GeneratedProtocolMessageType('Schema_MNIST_Input', (_message.Message,), dict(
  DESCRIPTOR = _SCHEMA_MNIST_INPUT,
  __module__ = 'bonsai.proto.curve_generator_pb2'
  # @@protoc_insertion_point(class_scope:bonsai.proto.curve_generator.Schema_MNIST_Input)
  ))
_sym_db.RegisterMessage(Schema_MNIST_Input)

Schema_MNIST_Output = _reflection.GeneratedProtocolMessageType('Schema_MNIST_Output', (_message.Message,), dict(
  DESCRIPTOR = _SCHEMA_MNIST_OUTPUT,
  __module__ = 'bonsai.proto.curve_generator_pb2'
  # @@protoc_insertion_point(class_scope:bonsai.proto.curve_generator.Schema_MNIST_Output)
  ))
_sym_db.RegisterMessage(Schema_MNIST_Output)

MNIST_training_data_schema = _reflection.GeneratedProtocolMessageType('MNIST_training_data_schema', (_message.Message,), dict(
  DESCRIPTOR = _MNIST_TRAINING_DATA_SCHEMA,
  __module__ = 'bonsai.proto.curve_generator_pb2'
  # @@protoc_insertion_point(class_scope:bonsai.proto.curve_generator.MNIST_training_data_schema)
  ))
_sym_db.RegisterMessage(MNIST_training_data_schema)


# @@protoc_insertion_point(module_scope)
